theme: jekyll-theme-cayman
title: COVID-19 Projections Using Machine Learning
description: "We take a data-driven approach rooted in epidemiology to forecast infections and deaths from the COVID-19 / coronavirus epidemic in the US and around the world"
show_downloads: true
google_analytics: UA-162990648-1
