theme: jekyll-theme-cayman
title: COVID-19 Projections Using Machine Learning
description: "Goal: To most accurately predict the peak and death totals of coronavirus (COVID-19) in the US and around the world"
show_downloads: true
