theme: jekyll-theme-cayman
title: COVID-19 Projections Using Machine Learning
description: "Harnessing artificial intelligence to most accurately predict infections and death totals of coronavirus (COVID-19) in the US and around the world"
show_downloads: true
google_analytics: UA-162990648-1
